src/Entity/Expense/Currency.php
<?php

namespace App\Entity\Expense;

use App\Repository\Expense\CurrencyRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CurrencyRepository::class)
 */
class Currency
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $code_currency;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $exchange_rate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity=ExpensesAccountLine::class, mappedBy="currency")
     */
    private $expensesAccountLines;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $symbole;

    public function __construct()
    {
        $this->expensesAccountLine = new ArrayCollection();
        $this->expensesAccountLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCodeCurrency(): ?string
    {
        return $this->code_currency;
    }

    public function setCodeCurrency(?string $code_currency): self
    {
        $this->code_currency = $code_currency;

        return $this;
    }

    public function getExchangeRate(): ?float
    {
        return $this->exchange_rate;
    }

    public function setExchangeRate(?float $exchange_rate): self
    {
        $this->exchange_rate = $exchange_rate;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|ExpensesAccountLine[]
     */
    public function getLineExpensesAccounts(): Collection
    {
        return $this->expensesAccountLine;
    }

    public function addLineExpensesAccount(ExpensesAccountLine $expensesAccountLine): self
    {
        if (!$this->expensesAccountLine->contains($expensesAccountLine)) {
            $this->expensesAccountLine[] = $expensesAccountLine;
            $expensesAccountLine->setCurrency($this);
        }

        return $this;
    }

    public function removeLineExpensesAccount(ExpensesAccountLine $expensesAccountLine): self
    {
        if ($this->expensesAccountLine->removeElement($expensesAccountLine)) {
            // set the owning side to null (unless already changed)
            if ($expensesAccountLine->getCurrency() === $this) {
                $expensesAccountLine->setCurrency(null);
            }
        }

        return $this;
    }

    public function getSymbole(): ?string
    {
        return $this->symbole;
    }

    public function setSymbole(?string $symbole): self
    {
        $this->symbole = $symbole;

        return $this;
    }

    /**
     * @return Collection|ExpensesAccountLine[]
     */
    public function getExpensesAccountLines(): Collection
    {
        return $this->expensesAccountLines;
    }

    public function addExpensesAccountLine(ExpensesAccountLine $expensesAccountLine): self
    {
        if (!$this->expensesAccountLines->contains($expensesAccountLine)) {
            $this->expensesAccountLines[] = $expensesAccountLine;
            $expensesAccountLine->setCurrency($this);
        }

        return $this;
    }

    public function removeExpensesAccountLine(ExpensesAccountLine $expensesAccountLine): self
    {
        if ($this->expensesAccountLines->removeElement($expensesAccountLine)) {
            // set the owning side to null (unless already changed)
            if ($expensesAccountLine->getCurrency() === $this) {
                $expensesAccountLine->setCurrency(null);
            }
        }

        return $this;
    }
}

src/Entity/Expense/ExpenseType.php
<?php

namespace App\Entity\Expense;

use App\Repository\Expense\ExpenseTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExpenseTypeRepository::class)
 */
class ExpenseType
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $code_type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity=ExpensesAccountLine::class, mappedBy="type")
     */
    private $expensesAccountLines;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $vat;

    public function __construct()
    {
        $this->expensesAccountLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCodeType(): ?string
    {
        return $this->code_type;
    }

    public function setCodeType(?string $code_type): self
    {
        $this->code_type = $code_type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getVat(): ?float
    {
        return $this->vat;
    }

    public function setVat(?float $vat): self
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * @return Collection|ExpensesAccountLine[]
     */
    public function getExpensesAccountLines(): Collection
    {
        return $this->expensesAccountLines;
    }

    public function addExpensesAccountLine(ExpensesAccountLine $expensesAccountLine): self
    {
        if (!$this->expensesAccountLines->contains($expensesAccountLine)) {
            $this->expensesAccountLines[] = $expensesAccountLine;
            $expensesAccountLine->setType($this);
        }

        return $this;
    }

    public function removeExpensesAccountLine(ExpensesAccountLine $expensesAccountLine): self
    {
        if ($this->expensesAccountLines->removeElement($expensesAccountLine)) {
            // set the owning side to null (unless already changed)
            if ($expensesAccountLine->getType() === $this) {
                $expensesAccountLine->setType(null);
            }
        }

        return $this;
    }
}

src/Entity/Expense/ExpensesAccountLine.php
<?php

namespace App\Entity\Expense;

use App\Repository\Expense\ExpensesAccountLineRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExpensesAccountLineRepository::class)
 */
class ExpensesAccountLine
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $billing_date;

    /**
     * @ORM\Column(type="float")
     */
    private $billing_amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_proof;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToOne(targetEntity=ExpenseType::class, inversedBy="expensesAccountLines")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Currency::class, inversedBy="expensesAccountLines")
     */
    private $currency;


    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $departure;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $arrival;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $kilometers;

    /**
     * @ORM\ManyToOne(targetEntity=Vehicle::class, inversedBy="expensesAccountLines")
     */
    private $vehicle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $establishment;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $amount_excl_VAT;

    /**
     * @ORM\Column(type="float")
     */
    private $total_amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $partner;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity=ExpensesAccount::class, inversedBy="expensesAccountLines")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end;

    public function __construct()
    {
        $this->isActive = 1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBillingDate(): ?\DateTimeInterface
    {
        return $this->billing_date;
    }

    public function setBillingDate(\DateTimeInterface $billing_date): self
    {
        $this->billing_date = $billing_date;

        return $this;
    }

    public function getBillingAmount(): ?float
    {
        return $this->billing_amount;
    }

    public function setBillingAmount(float $billing_amount): self
    {
        $this->billing_amount = $billing_amount;

        return $this;
    }

    public function getUrlProof(): ?string
    {
        return $this->url_proof;
    }

    public function setUrlProof(?string $url_proof): self
    {
        $this->url_proof = $url_proof;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getType(): ?ExpenseType
    {
        return $this->type;
    }

    public function setType(?ExpenseType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getDeparture(): ?string
    {
        return $this->departure;
    }

    public function setDeparture(?string $departure): self
    {
        $this->departure = $departure;

        return $this;
    }

    public function getArrival(): ?string
    {
        return $this->arrival;
    }

    public function setArrival(?string $arrival): self
    {
        $this->arrival = $arrival;

        return $this;
    }

    public function getKilometers(): ?float
    {
        return $this->kilometers;
    }

    public function setKilometers(?float $kilometers): self
    {
        $this->kilometers = $kilometers;

        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): self
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getEstablishment(): ?string
    {
        return $this->establishment;
    }

    public function setEstablishment(?string $establishment): self
    {
        $this->establishment = $establishment;

        return $this;
    }

    public function getAmountExclVAT(): ?float
    {
        return $this->amount_excl_VAT;
    }

    public function setAmountExclVAT(?float $amount_excl_VAT): self
    {
        $this->amount_excl_VAT = $amount_excl_VAT;

        return $this;
    }

    public function getTotalAmount(): ?float
    {
        return $this->total_amount;
    }

    public function setTotalAmount(float $total_amount): self
    {
        $this->total_amount = $total_amount;

        return $this;
    }

    public function getPartner(): ?string
    {
        return $this->partner;
    }

    public function setPartner(?string $partner): self
    {
        $this->partner = $partner;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAccount(): ?ExpensesAccount
    {
        return $this->account;
    }

    public function setAccount(?ExpensesAccount $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }
}

templates/Expense/addLineExpenses.html.twig
{% extends '_include/Back/_layout.html.twig' %}
{% block title %}Ajout d'un frais {% endblock %}
{% block content %}

<h3 class="mb_2 header_title">Déclaration de frais  {{ expenseAccount.name }} </h3>

<div class="form-group">

    {{ form_start(formAddLineExpense, {'attr':{'id': 'formAddLineExpense'}}) }}
        <div class='row' id="commonForm">
            <div class="col-4"> {{ form_row(formAddLineExpense.type)}}</div>
            <div class="col-8"> {{ form_row(formAddLineExpense.description)}}</div>
        </div>
        <div class="row" id="expensePartners">
            <div class="col-12"> {{ form_row(formAddLineExpense.partner) }} </div>
            <div class="col-4"> {{ form_row(formAddLineExpense.billing_date)}}</div>
            <div class="col-8">{{ form_row(formAddLineExpense.establishment) }}</div>
        </div>
        <div class="row" id="businessTripForm">
            <div class="col-6" > {{ form_row(formAddLineExpense.start)}}</div>
            <div class="col-6" > {{ form_row(formAddLineExpense.end)}}</div>
            <div class="col-6" > {{ form_row(formAddLineExpense.departure)}}</div>
            <div class="col-6" > {{ form_row(formAddLineExpense.arrival)}}</div>
            <div class="col-6" > {{ form_row(formAddLineExpense.kilometers)}}</div>
            <div class="col-6" > {{ form_row(formAddLineExpense.vehicle)}}</div>
        </div>
        <div class="row">
            <div class="col-4 amount-param" id="form_group_billing_amount"> {{ form_row(formAddLineExpense.billing_amount)}}</div>
            <div class="col-4 amount-param"> {{ form_row(formAddLineExpense.currency)}}</div>
            <div class="col-4" id="add_line_expense_convert_amount">{{ form_row(formAddLineExpense.total_amount) }}</div>
        </div>

        <div class="row">
            <div class="col-12"> {{ form_row(formAddLineExpense.comment)|raw }}</div>
        </div>
        <div class="row">
            <button type="button" class="btn btn-secondary btn-sm">Annuler</button>
            <button type="button" class="btn_add btn-secondary btn-sm" id="btnSubmitFormExpense">Enregistrer</button>
        </div>
    {{ form_end(formAddLineExpense) }}
</div>


{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function (){
            //properties
            let rate = 1;
            let amount = 0;
            let total_amount = null;
            let symbol_zone = $("#form_group_billing_amount span");
            let kms = null;

            // display init
            $("#add_line_expense_convert_amount").hide();
            $("#businessTripForm").hide();
            $("#add_line_expense_billing_date").datepicker({
                language: 'fr',
                format:'yyyy-mm-dd',
                startDate:'{{ expenseAccount.start|date('Y-m-d') }}',
                endDate:'{{ expenseAccount.end|date('Y-m-d') }}'
            })

            // amount validate
            $("#add_line_expense_billing_amount").change(function(){
                amount = parseFloat($(this).val());
                if(amount>0 && !isNaN(amount)) {
                    total_amount = convertAmount(amount, rate);
                    $("#add_line_expense_total_amount").val(total_amount.toFixed(2));
                }
            })

            // total amount validate


            //currency rate
            $("#add_line_expense_currency").change(function(){
                let search_currency_url =  "{{ url('back_search_currency', {'id':'__0__'}) }}";
                search_currency_url = search_currency_url.replace('__0__', $(this).val());
                $.ajax({
                    method:"GET",
                    url : search_currency_url,
                    dataType: 'json',
                    success: function (data){
                        rate = data.exchange_rate;
                        let code = data.code;
                        if(code !== 'eur'){
                            $("#add_line_expense_convert_amount").show();
                            total_amount = convertAmount(amount, rate);
                            $("#add_line_expense_total_amount").val(total_amount.toFixed(2));
                            symbol_zone.text(data.symbole);
                        }else{
                            $("#add_line_expense_convert_amount").hide();
                            total_amount = convertAmount(amount, rate);
                            $("#add_line_expense_total_amount").val(total_amount.toFixed(2));
                            symbol_zone.text(data.symbole);
                        }
                    }
                    }
                )
            })

            // expense type form
            $("#add_line_expense_type").change(function (){
                let search_type_url =  "{{ url('back_search_expense_type', {'id':'__0__'}) }}";
                search_type_url = search_type_url.replace('__0__', $(this).val());
                $.ajax({
                    method:'GET',
                    url: search_type_url,
                    dataType: 'json',
                    success: function(data){
                        if(data.code==='trav'){
                            $("#businessTripForm").slideDown(1000);
                            $("#expensePartners").slideUp(1000);
                            $(".amount-param").slideUp(1000);
                            $("#add_line_expense_convert_amount").slideDown(1000);
                            $("#add_line_expense_total_amount").val(null);
                            $("#add_line_expense_kilometers").val(null);
                        }else{
                            $("#businessTripForm").slideUp(1000);
                            $("#expensePartners").slideDown(1000);
                            $(".amount-param").slideDown(1000);
                            $("#add_line_expense_convert_amount").hide();
                            $("#add_line_expense_total_amount").val(null);
                            $("#add_line_expense_billing_amount").val(null);
                            $("#add_line_expense_currency").val(1);
                            symbol_zone.text('€');

                        }
                    }
                })
            })

            // validate kilometers
            $("#add_line_expense_kilometers").change(function (){
                kms = parseFloat($(this).val());
                if(kms>0 && !isNaN(kms)){
                    let search_vehicle_url =  "{{ url('back_search_vehicle', {'id':'__0__'}) }}";
                    search_vehicle_url = search_vehicle_url.replace('__0__', $("#add_line_expense_vehicle").val());
                    $.ajax({
                        method:"GET",
                        url : search_vehicle_url,
                        dataType: 'json',
                        success: function (data) {
                            total_amount=data.allowance*kms;
                            $("#add_line_expense_total_amount").val(total_amount.toFixed(2));

                        }
                    })
                }
            })

            $("#add_line_expense_vehicle").change(function(){
                let search_vehicle_url =  "{{ url('back_search_vehicle', {'id':'__0__'}) }}";
                search_vehicle_url = search_vehicle_url.replace('__0__', $(this).val());
                $.ajax({
                    method:"GET",
                    url : search_vehicle_url,
                    dataType: 'json',
                    success: function (data) {
                        total_amount=data.allowance*kms;
                        $("#add_line_expense_total_amount").val(total_amount.toFixed(2));
                    }
                })
            })

            $("#btnSubmitFormExpense").click(function(){
                // if(total_amount>0 && !isNaN(total_amount)){
                    $(this).html(btn_spin);
                    $('#formAddLineExpense').submit();
                    // $("#formAbtnSubmitFormExpense
                // }
            })

            // function convert
            function convertAmount(amount, rate) {
                let result;
                return result = amount * rate;
            }
        })
    </script>
{% endblock %}

templates/Expense/listLineExpenses.html.twig
{% extends '_include/Back/_layout.html.twig' %}

{% block title %}Détails des frais {% endblock %}
{% block content %}

<h3 class="mb_2 header_title">Listes des frais {{ expenseAccount.name }}</h3>
<div class="header_btn_container">
    <a href="{{ path('back_add_line_expense',{'id': expenseAccount.id }) }}" class="btn_add"><i class="fa fa-plus"></i>&nbsp;Ajouter</a>
</div>
<div class="tab-content">
    <table id="linesExpenses_list" class="display dataTable " style="width:100%">
        <thead>
        <tr>
            <th>Id</th>
            <th>Description</th>
            <th>Type</th>
            <th>Date</th>
            <th>Montant</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for line in expenseAccount.lineExpensesAccounts %}
            <tr data-leid="{{ line.id }}">
                <td>{{ line.id }}</td>
                <td class="display-account">{{ line.description }}</td>
                <td>{{ line.type.name }}</td>
                <td>{{ line.billingDate|date('d-m-Y') }}</td>
                <td>{{ line.billingAmount }}€</td>
                <td>
                    <button type="button" class="btn_edit btn_round btn_edit_expense"><i class="fa fa-edit"></i></button>
                    <button type="button" class="btn_mail btn_round btn_duplicate_expense"><i class="fa fa-copy"></i></button>
                    <button type="button" class="btn-danger btn_round btn_delete_expense"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}

{% block javascripts %}
<script>
    let ready = $(document).ready(function (){
        let current_tr = "";
        let current_id="";

        $('#linesExpenses_list').DataTable({
            language: obj_dt_translation.fr_FR
        });

        $(".btn_edit_expense").click(function(){
            current_tr = $(this).closest('tr');
            current_id = $(current_tr).data("leid");
            console.log($(current_id));
        })
    })


</script>

{% endblock %}